title: Nikhil Patel
logo: /assets/img/logo.png
description: Innovative IT professional offering vast experience leveraging software engineering and Agile/ DevOps methodologies to deliver highly effective and creative solutions to business and technological challenges. Utilizes highly attuned analytical skills to develop IT and business strategies employing cutting-edge technologies to increase productivity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
